#!/usr/bin/env bash

set -e;

if [ ! -d "secrets" ]; then
  echo "Error: missing \"secrets\" directory." >&2;
  echo "Please run: \"decrypt-secrets\"" >&2;
  exit 1;
fi

if [ ! -f "secrets/secrets.version" ]; then
  echo "Error: \"secrets\" is out of date." >&2;
  echo "Please run \"decrypt-secrets\"" >&2;
  exit 1;
fi

encrypted_version=$(cat secrets.lock);
decrypted_version=$(cat secrets/secrets.version);

if test "$decrypted_version" -lt "$encrypted_version"; then
  echo "Error: \"secrets\" is out of date." >&2;
  echo "Please run: \"decrypt-secrets\"" >&2;
  exit 1;
fi
