#!/usr/bin/env bash

set -e;

gpg_cmd=$(which gpg 2> /dev/null || echo -n);
if [ -z "$gpg_cmd" ]; then
  echo "Could not locate the \"gpg\" command" >&2;
  echo "Please run: \"brew install gpg\"" >&2;
  exit 1;
fi

if [ ! -f "secrets.tar.gz.gpg" ]; then
  echo "Error: no \"secrets.tar.gz.gpg\" found." >&2;
  echo "Did you forget to run \"encrypt-secrets\"?" >&2;
  exit 1;
fi

if [ -z "${SECRETS_PASSPHRASE}" ]; then
  echo "\"SECRETS_PASSPHRASE\" not found in your environment" >&2;
  exit 1;
fi

${gpg_cmd} \
  --quiet \
  --batch \
  --cipher-algo ${SECRETS_CIPHER_ALGO:-"AES256"} \
  --passphrase "${SECRETS_PASSPHRASE}" \
  secrets.tar.gz.gpg;

rm -rf secrets;
cat secrets.tar.gz | gunzip | tar x;
rm -f secrets.tar.gz;
