#!/usr/bin/env bash

set -e;

gpg_cmd=$(which gpg 2> /dev/null || echo -n);
if [ -z "$gpg_cmd" ]; then
  echo "Could not locate the \"gpg\" command" >&2;
  echo "Please run: \"brew install gpg\"" >&2;
  exit 1;
fi

if [ ! -d "secrets" ]; then
  echo "Error: no \"secrets\" directory found." >&2;
  echo "Did you forget to run \"decrypt-secrets\"?" >&2;
  exit 1;
fi

if [ ! -e "secrets/secrets.version" ]; then
  echo 0 > secrets/secrets.version;
fi

expr $(cat secrets/secrets.version) + 1 > secrets/secrets.version;
cp secrets/secrets.version secrets.lock;

tar c secrets | gzip > secrets.tar.gz;
rm -f secrets.tar.gz.gpg;

if [ -z "${SECRETS_PASSPHRASE}" ]; then
  echo "\"SECRETS_PASSPHRASE\" not found in your environment" >&2;
  exit 1;
fi

${gpg_cmd} \
  --quiet \
  --batch \
  --cipher-algo ${SECRETS_CIPHER_ALGO:-"AES256"} \
  --passphrase "${SECRETS_PASSPHRASE}" \
  --symmetric secrets.tar.gz;

rm -f secrets.tar.gz;
